services:
  frontend:
    image: <acr>.azurecr.io/nextbook-frontend:latest
    environment:
      - NODE_ENV=production
    expose:
      - "3001"

  nginx:
    image: <acr>.azurecr.io/nextbook-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
